language: python
python:
  - "3.3"
  - "2.7"
  - "2.6"

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes --quiet conda

install:
  - conda create --yes --quiet -n tools-test nose numpy pandas
  - source activate tools-test
  - if [ ${COVERAGE} = true ]; then pip install coverage coveralls; fi
  - python setup.py install

script:
  - cd timeseriestools
  - cd tests
  - nosetests